### ISSUE TITLE
Is region cover functioning? Can i check proximity to polyline?

### ISSUE THREAD

**Issue by alexahlen** [philip-bui/s2-geometry-swift#6]
Hi

Thanks for porting over this library!

Ive been looking through all the documentation, and google documentation and im not sure if im missing something, or there are a few classes still missing?

Has the region cover been implemented? I can see the class exists, but im not sure what parameters to put in. S2 region? It doesnt seem to exist.

Basically what im trying to do is search for the closest locations to a route. I see two ways to achieve this. 1) check for the closest points to a polyline, or 2) check for points in a polygon.
Can i achieve either of these?

Sorry to ask here, but i cant find a single geo-hash-like library way to do this for swift. 

Thanks!

**Comment by philip-bui** [comment]
Hi @alexahlen ,

With this library, I would imagine you would search for points in a polygon, then sort them to get your closest locations. 

You would use S2Polyline class(S2Region is a protocol) in the S2RegionCoverer class, and choosing [map cells of varying sizes](http://s2geometry.io/resources/s2cell_statistics.html), create your polygon to search for your points. 

The only problem is you are bounded by the search area, too small with no results and you will have to search again and too large and you will need to sort more elements. 

Alternatively if you always require N closest points, you can also use R-Tree (automatically sorting and grouping points close to each other on each insert).

Unfortunately S2Polyline hasn't been implemented, if you require it I can look to implement it over the next weekend. I imagine it would look like

```swift
public init(points: [S2LatLng]) {

}
```

Try playing with this [example](https://s2.sidewalklabs.com/regioncoverer/) for map cell sizes to see if it will fit your use case (they use rectangles instead of a polyline).

**Comment by alexahlen** [comment]
Hi

Thanks for getting back to me and for your suggestions.

I did a good few hours of research into r-trees, and i still have a number of questions. The primary ones are would it be effectively used with Firestore, but more importantly, i cant find any swift libraries for it. (If i can i would prefer to use better written software from experts in the field more knowledgeable than I). It seems to be there are not many people using it for my specific purpose in an easy to use package (although it is widely used). There seems to be far more documentation on geohashes for example for my use case. If you know of any libraries let me know, as you say it might be more effective.

Otherwise i think the S2 library would be the (second?) most effective option. Even if KNN is not its biggest strength. The main thing im looking for is its algorithm for creating hashes (its area covering algorithm - over polyline or polygon, whichever is best). I read it is quite good, and my current implementation is... not. Very brute force i think. 

In the meantime i managed to hack together a mix of a basic geohashing library with a Geographic Engine (GEOSwift) which works, but i suspect is crazy inefficient. I could also try and improve efficiency of this, it works okish in the short run.

Also - im developing for iOS so on device processing (for creating a search area) would have to be quick and minimal but should be a non issue as GeoFire exists and works well.

Sorry i know this is not really your problem, but it seems after ~2012-2015 there has been a loss of interest in spacial indexing and there are not much up-to-date easy to follow information so someone else's take is useful. Also swift libraries are non-existent for if you dig deep for this use case.

Let me know what you think. thanks again.

**Comment by philip-bui** [comment]
Hi @alexahlen 

Not a problem, I used to do geospatial work so I understand.

Onto your point, SQL (Postgres and MySQL, PostGIS) both have R-Tree implementations, and I would have to ask are you storing R-Tree in memory (hence the need for a Swift library)? I believe https://developer.apple.com/documentation/gameplaykit/gkrtree is an official implementation by Apple. PostGIS also supports GeoHashes and KNN querying I believe.

Both GeoHash and S2 index data by approximating the world into squares (or rects), so the same problem will still apply. See [here](https://angularfirebase.com/lessons/geolocation-query-in-firestore-realtime/). GeoHash is more widely supported so there is less work, but there are efficiency gains in comparing and storing ints.

You can have a look at [S2CellID](https://github.com/philip-bui/s2-geometry-swift/blob/bee6f73d0a4eb99417da367ba7e58f86d6b58eca/Sources/Classes/S2CellId.swift#L140) 
 methods to see how it hashes, but I would just use S2 in that case.

Creating hashes and search areas is quite efficient, so I don't imagine there will be problems even at millions. I haven't used GEOSwift so I can't comment on that.

Hope this answers your questions.

**Comment by alexahlen** [comment]
Im not quite sure if im answering your question here but:

Im storing the hashes online (serverless in firestore) but i have to calculate the hashes to search firestore for on-device and while the user waits (near-instantaneous). I create a polyline (a route), which i create a buffer around, and fill that shape with hashes, then search for those hashes on firestore, the less hashes the better as each one costs me (hence my need to reduce hashes). From what ive read the implementation of r-trees would be somewhat similar - i.e. calculate on device to search in Firestore? Basically i cant use server-extension software and calculate on a server if that is what you are suggesting. 

I saw the gkrtree but didnt know it could be applied to geospacial queries. Tutorials for this are few and far between but ill have another look, seems like it could work.

I think what ill do is see if i can find some good tutorials on r-trees, if i can attempt that. If not either stay with my current implementation or move over to your s2 library if its more efficient. 

The problems started for me in the 10s of thousands i believe. I know as my v1.0 of my algorithm was calculating exponential amounts of hashes ha! (but i think its to do with my point-in-polygon check).

Anyway let me know if ive misunderstood something, otherwise thanks for the help and ill see how i get on! And thanks again for porting over the library.
