### ISSUE TITLE
How to use s2-geometry-swift?

### ISSUE THREAD

**Issue by NickAtGit** [philip-bui/s2-geometry-swift#7]
Is there any example code or tutorial on how to use this library? I couldn't find any good resources...

I would like to make a simple app where you can load locations from a server based on s2 geometries.

**Comment by philip-bui** [comment]
Hi @NickAtGit ,

http://s2geometry.io/ would be the closest thing to official documentation, there are a few articles around, but the best way would be to play around with the library for a bit. I think the S2Cell, S2CellID S2RegionCoverer and S2Rect will cover your use cases.

Try hashing your locations into Level 30 CellIDs(smallest cells) for storage, and for querying use RegionCoverer to create your query CellIDs. At its heart, S2Cells are based off quad-tree with each cell having its own unique id (each level of quad requiring 4 bits, smaller cells using more bits etc.), so you can query any sized cells for your locations by setting and unsetting your children bits.

Hope that helps you.
