### ISSUE TITLE
RegionCoverer/S2CellUnion.denormalize gets stuck in a loop

### ISSUE THREAD

**Issue by SFrost007** [philip-bui/s2-geometry-swift#8]
**Describe the bug**
Thanks for this library! I'm trying to make an iOS app that will cover a MapView with a rendering of S2 cells, specifically at level 17. I've written a prototype which attempts to do this, but depending on the region and and minimum/maximum levels it gets stuck in the `while` loop inside `S2CellUnion.denormalize` consuming increasing amounts of memory until the app crashes.

For the test region hardcoded in the sample below it works fine with minLevel 15 and maxLevel 17, but bumping the minimum up to 16 causes the bug. In some map locations a minimum of 16 works, but I've not been able to get `minLevel = maxLevel = 17` to work anywhere.

I understand if there are limits on the scale it's feasible to generate cells covering (and will likely impose such limits in the app), but in this case I'm testing with a reasonably small coverage area. Web-based implementations such as the [SidewalkLabs Region Coverer](https://s2.sidewalklabs.com/regioncoverer/) seem to handle this fine.

If there's a more optimal way of simply rendering a grid of fixed-level cells I'd be more than happy to try it. I'm not particularly familiar with S2Geography (or GIS in general) so I may well be missing something obvious, or over-complicating things!

**To Reproduce**
```swift
// Get the extent of the visible area of the MapView to fill with data
// Note: Hardcoded with known-bad test values
let center = CLLocationCoordinate2D(latitude: 52.283656780399156, longitude: -1.520304499700842)
let span = MKCoordinateSpan(latitudeDelta: 0.0058, longitudeDelta: 0.0043)
let tl = CLLocationCoordinate2D(latitude: center.latitude - span.latitudeDelta, longitude: center.longitude - span.longitudeDelta)
let br = CLLocationCoordinate2D(latitude: center.latitude + span.latitudeDelta, longitude: center.longitude + span.longitudeDelta)

// Convert this into S2Geometry objects and configure the cell size
let s2tl = S2LatLng.fromDegrees(lat: tl.latitude, lng: tl.longitude)
let s2br = S2LatLng.fromDegrees(lat: br.latitude, lng: br.longitude)
let s2rect = S2LatLngRect(lo: s2tl, hi: s2br)
let coverer = S2RegionCoverer()
coverer.minLevel = 16 // Should be 17 in final version. 15 works.
coverer.maxLevel = 17
coverer.maxCells = 1000

// Get the cells and convert them to MKPolygon overlays.
let cellIDs = coverer.getCovering(region: s2rect)
// Limit to unique CellIDs so we don't render multiple overlays at the same point
let uniqueIDs = Array(Set(cellIDs))
for cellID in uniqueIDs {
    let cell = S2Cell(cellId: cellID)
    var corners: [CLLocationCoordinate2D] = []
    for i in 0..<4 {
        let s2ll = S2LatLng(point: cell.getVertex(i))
        corners.append(CLLocationCoordinate2D(latitude: s2ll.lat.degrees, longitude: s2ll.lng.degrees))
    }
    mapView.addOverlay(MKPolygon(coordinates: corners, count: corners.count))
}
```

**Expected behavior**
`coverer.getCovering()` returns results in a reasonable time.

**Actual behavior**
App hangs, then eventually crashes with a `malloc` error.

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: iOS 13.2.3

**Additional context**
Also occurs on simulator builds.

**Comment by philip-bui** [comment]
Hi @SFrost007 ,

Looks like there is a few hundred thousand "cells" in that covering, even though you specified a maxCell size of 1000. If you specified minLevel = 0, it starts respecting the maxCell property.

I'm not too sure of what the fix here, if your idea is to render an area with the same cell sizes, you can set your region coverer's maxCells = 5 and minLevel = 0, it will usually result in same cell sizes.

If your idea is to render any area with level 17 cell sizes, you will run into issues with any language's implementation of S2 (I just checked Go and Java).

If you can describe of what you're trying to achieve, I can try to give you a better solution.
